spring.application.name=fullclean

# 1. Configuração do PostgreSQL (Inventário e Transações - O BD ACID)
# O host (joias_inventario) deve ser o nome do seu container Docker, conforme configurado na sua rede.
spring.datasource.url=jdbc:postgresql://joias_inventario_db:5432/joias_saas_db
spring.datasource.username=postgres
spring.datasource.password=2468
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações JPA/Hibernate para Multi-tenancy
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.multiTenancy=DATABASE
spring.jpa.properties.hibernate.tenant_identifier_resolver=com.fullclean.config.TenantIdentifierResolver

# 2. Configuração do Redis (Cache - O BD BASE de Velocidade)
# O host (joias-redis) deve ser o nome do seu container Redis.
spring.data.redis.host=joias-redis
spring.data.redis.port=6379

# 3. Configuração do Nome da Aplicação 
spring.application.name=joias-saas-backend

# 4. Habilitar o Spring a encontrar o seu filtro (Etapa 3)
spring.servlet.multipart.enabled=true

# Configuração do Banco de Dados H2 em memória para o teste (Manter para testes locais)
spring.datasource.url.h2=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName.h2=org.h2.Driver
spring.datasource.username.h2=sa
spring.datasource.password.h2=
spring.jpa.database-platform.h2=org.hibernate.dialect.H2Dialect

# Desabilitar a segurança padrão do Spring Security para facilitar o teste
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
